requirements:
  profile: default
  add:
    buckets:
      - trequire-tool-test
    dynamodb:
      - trequire-tool-test
    user: trequire-tool-test
  # remove:
  #   buckets:
  #     - trequire-tool-test
  #   dynamodb:
  #     - trequire-tool-test
  #   user: trequire-user